project:
  type: website

website:
  title: "GPD Américas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: "#b0c7c4"
    foreground: "#628089"

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: "Source Serif 4"
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>



