---
title: "Giving"
format: 
  html:
    tbl-cap-location: bottom
    toc: true
  pdf: default

---

<h2 style="font-size: 18px; margin-top: 5px;">Support the Generation of Participation in Democracy</h2>

Your support enables the development of sustainable, participatory institutions
across the Americas. Currently, 100% of contributions go to fund research, field programs, and infrastructure through our Flagship Institute, Instituto Dourados.
Once we can fund the first two years of operation of Instituto Dourados we may
consider expanding GPD's institutional portfolio, allocating resources
beyond just Instituto Dourados.

Opportunities to support other GPD Américas organizations will be announced as
they become available.

## Contribution Tiers

The following table lists the minimum contribution for six tiers of support.
Different tiers have different perks, as indicated by superscripts and 
explained following the table.

| Tier     | Min. Contribution | Description         |
|----------|------------|-----------------------|
| Founder$^{1,2,3}$  | \$1,000,000          | Institutional founding support |
| Platinum$^{1,2,3}$ | \$100,000            | Major program sponsorship |
| Gold$^{1,2,3}$     | \$10,000             | Program and research support |
| Silver$^{1,2}$   | \$1,000              | Travel and entry-level salary  |
| Reader$^{1}$   | \$100            | Help pay infrastructure costs |
| Hero     | ≥ \$1                | Help as you are able, and you're our hero |


### Explanation of Tiers

1. Includes one-year subscription Instituto Dourados Quarterly Journal. 
2. The donor's name, or the name of someone the donor wants to honor, will be
   published on the website. The donor may add a short message as well.
3. These tiers are classified as a _Major Contribution_ at GPD. Please contact
   our giving team to make personalized arrangements:
   [giving@gpdamericas.org](mailto:giving@gpdamericas.org). We will be happy to
   welcome you as a Generation of Participation in Democracy partner if it is
   indeed a good fit for both parties.


## Donate

For donations less than \$1000, please donate to our current fundraising sprint
to avoid founder burnout via GoFundMe:


<div class="gfm-embed" data-url="https://www.gofundme.com/f/launch-an-exchange-program-to-boost-indigenous-public-health/widget/large?sharesheet=undefined&attribution_id=sl:ba86e4ce-71f4-4aab-b267-c30e9bf546a7"></div><script defer src="https://www.gofundme.com/static/js/embed.js"></script>


## Major Contributions

Founder, Platinum, Gold, and Silver contributions are coordinated directly to
align with specific programs and reporting. Please contact our Giving team to
make arrangements.

- **GPD Américas — Giving**  
  [giving@gpdamericas.org](mailto:giving@gpdamericas.org)

## Transparency

All contributions are governed under our public benefit mission and transparency
principles. Currently anticipated budget allocations and funding scenarios are
published on the Instituto Dourados page.

- **GPD Américas — Transparency**  
  [transparency@gpdamericas.org](mailto:transparency@gpdamericas.org)
